config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos, only: %i(index show new edit)

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit]

  # GET /todos
  # GET /todos.json
  def index
    @todos = []
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.new(id: params[:id])
    end

    # # Never trust parameters from the scary internet, only allow the
    # # white list through.
    # def todo_params
    #   params.require(:todo).permit(:title, :content, :todo_date)
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  IGNORE_RAILS_BEST_PRACTICES = 1
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
      <%= content_for?(:title) ? yield(:title) : "BrowserifyRailsApp" %>
    </title>

    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script
        src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
        type="text/javascript">
      </script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag('apple-touch-icon-144x144-precomposed.png',
                         rel: 'apple-touch-icon-precomposed', type: 'image/png',
                         sizes: '144x144') %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag('apple-touch-icon-114x114-precomposed.png',
                         rel: 'apple-touch-icon-precomposed', type: 'image/png',
                         sizes: '114x114') %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag('apple-touch-icon-72x72-precomposed.png',
                         rel: 'apple-touch-icon-precomposed', type: 'image/png',
                         sizes: '72x72') %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag('apple-touch-icon-precomposed.png',
                         rel: 'apple-touch-icon-precomposed',
                         type: 'image/png') %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>

    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= controller_name -%> <%= action_name -%>">
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target=".navbar-responsive-collapse">

          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">BrowserifyRailsApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/todos/_form.html.erb
<%= simple_form_for todo, html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :title, input_html: { class: 'validate[required,minsize[1]]' } %>
  <%= error_span(todo[:title]) %>
  <%= f.input :content %>
  <%= error_span(todo[:content]) %>
  <%= f.input :todo_date %>
  <%= error_span(todo[:todo_date]) %>

  <%= link_to(t('.submit', default: t('helpers.submit.create')),
              '#', class: 'btn btn-primary', id: :submit) %>

  <%= link_to(t('.cancel', default: t('helpers.links.cancel')),
              todos_path, class: 'btn btn-default') %>
<% end %>

app/views/todos/edit.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1>
    <%= t('.title',
          default: [:'helpers.titles.edit', 'Edit %{model}'],
          model: model_class.model_name.human.titleize) %>
  </h1>
</div>
<div hidden id="todo_id"><%= @todo.id %></div>
<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1>
    <%= t('.title', default: model_class.model_name.human.pluralize.titleize) %>
  </h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:todo_date) %></th>
      <th><%=t '.actions', default: t('helpers.actions') %></th>
    </tr>
  </thead>

  <tbody id="todo_rows">
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to todo.title, todo_path(todo) %></td>
        <td><%= todo.content %></td>
        <td><%= todo.todo_date %></td>
        <td>
          <%= link_to(t('.edit', default: t('helpers.links.edit')),
                      edit_todo_path(todo), class: 'btn btn-default btn-xs') %>

          <% d = { confirm: t('.confirm',
                              default: t('helpers.links.confirm',
                                         default: 'Are you sure?')) } %>

          <%= link_to(t('.destroy', default: t('helpers.links.destroy')),
                      todo_path(todo),
                      method: :delete,
                      data: d,
                      class: 'btn btn-xs btn-danger') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to(t('.new', default: t('helpers.links.new')),
            new_todo_path,
            class: 'btn btn-primary') %>

app/views/todos/new.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1>
    <%= t('.title',
          default: [:'helpers.titles.new', 'New %{model}'],
          model: model_class.model_name.human.titleize) %>
  </h1>
</div>
<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<%- model_class = Todo -%>
<div hidden id="todo_id"><%= @todo.id %></div>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd id="title"><%= @todo.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd id="content"><%= @todo.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:todo_date) %>:</strong></dt>
  <dd id="date"><%= @todo.todo_date %></dd>
</dl>

<%= link_to t('.back', default: t("helpers.links.back")),
              todos_path, class: 'btn btn-default'  %>

<%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_todo_path(@todo), class: 'btn btn-default' %>

<%= link_to(t('.destroy', default: t('helpers.links.destroy')), '#',
            id: :delete,
            class: 'btn btn-danger') %>